//! The worm's body: a segmented crawler.
//!
//! Deliberately *not* the fly with different geometry. A worm has no legs, no
//! wings and no flight, so there is no gait phase, no altitude and no takeoff —
//! which is exactly why [`crate::creature::Body`] is a trait rather than a
//! struct with feature flags (PORT_PLAN.md §5).
//!
//! Locomotion is a travelling wave. The head oscillates side to side and its
//! trajectory is *recorded*; the body is that recorded path, sampled at fixed
//! arc-length intervals. Each segment therefore retraces exactly where the head
//! has been, which is how the animal actually moves, and it gives correct
//! undulation for free.
//!
//! The path history is not an optimisation — it is what makes reversal real.
//! A naive chain of distance constraints looks right going forward, but backing
//! it up merely *straightens* the body: pull one end and the links pivot into a
//! line instead of retracing the curve. Measured on the first attempt, the tail
//! moved 6 units while the head moved 0.5. With a path, reversal is just
//! sliding the sample point backwards along the track the worm already made.
//!
//! Proprioception is first-class here in a way it is not for the fly. *C.
//! elegans* undulation is generated by proprioceptive coupling along the body —
//! B-type motor neurons respond to local curvature — so the body is not a
//! display of the network's output, it is part of the circuit.

use crate::creature::{Body, Proprioception, Substrate, World};
use crate::rng::Pcg32;
use crate::signals::BrainSignals;
use crate::util::{clamp, Vec2};

/// Number of body points. 24 reads as a smooth curve at desktop scale without
/// costing anything.
pub const SEGMENTS: usize = 24;
/// Distance between adjacent body points, in scene units.
pub const SEGMENT_LEN: f32 = 2.6;
/// Body length, for sizing and for the head/tail touch test.
pub const BODY_LEN: f32 = SEGMENT_LEN * (SEGMENTS as f32 - 1.0);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WormState {
    Forward,
    Reversing,
    /// The sharp turn that follows a reversal — the second half of a pirouette.
    OmegaTurn,
    Quiescent,
}

pub struct Worm {
    pub pos: Vec2,
    pub heading: f32,
    pub state: WormState,
    /// Undulation phase, 0..1.
    pub phase: f32,
    /// Body points, head first. Derived from `path`; never edited directly.
    pub body: Vec<Vec2>,
    /// The track the head has traced, oldest first.
    path: Vec<Vec2>,
    /// Cumulative arc length along `path`.
    arc: Vec<f32>,
    /// Arc-length position of the head along `path`.
    head_s: f32,
    pub speed: f32,
    /// Seconds remaining in the current reversal or turn.
    pub reverse_timer: f32,
    pub turn_timer: f32,
    /// Locomotor drive last applied, 0..1 — drives the undulation frequency.
    pub drive: f32,
    pub time: f32,
    rng: Pcg32,
}

impl Worm {
    pub fn new(at: Vec2, seed: u64) -> Self {
        let mut rng = Pcg32::new(seed);
        let heading = rng.range(0.0, std::f32::consts::TAU);
        // Seed the path with a straight run behind the head, so the body has
        // somewhere to be on frame one.
        let start = BODY_LEN * 1.5;
        let tail = Vec2::new(
            at.x - heading.cos() * start,
            at.y - heading.sin() * start,
        );
        let path = vec![tail, at];
        let arc = vec![0.0, start];
        let body = (0..SEGMENTS)
            .map(|i| {
                Vec2::new(
                    at.x - heading.cos() * SEGMENT_LEN * i as f32,
                    at.y - heading.sin() * SEGMENT_LEN * i as f32,
                )
            })
            .collect();
        Worm {
            pos: at,
            heading,
            state: WormState::Forward,
            phase: rng.range(0.0, 1.0),
            body,
            path,
            arc,
            head_s: BODY_LEN * 1.5,
            speed: 0.0,
            reverse_timer: 0.0,
            turn_timer: 0.0,
            drive: 0.0,
            time: rng.range(0.0, 100.0),
            rng,
        }
    }

    /// Local curvature at each body point, which is what the B-type motor
    /// neurons sense. Positive is a bend to the left.
    pub fn curvature(&self) -> Vec<f32> {
        let mut out = vec![0.0; self.body.len()];
        for i in 1..self.body.len() - 1 {
            let a = self.body[i - 1];
            let b = self.body[i];
            let c = self.body[i + 1];
            let v1 = Vec2::new(b.x - a.x, b.y - a.y);
            let v2 = Vec2::new(c.x - b.x, c.y - b.y);
            // Signed turn between consecutive segments.
            out[i] = (v1.x * v2.y - v1.y * v2.x)
                / (SEGMENT_LEN * SEGMENT_LEN).max(1e-4);
        }
        out
    }

    /// The head end while crawling forward, the tail end while reversing.
    pub fn leading_point(&self) -> Vec2 {
        if self.state == WormState::Reversing {
            *self.body.last().unwrap_or(&self.pos)
        } else {
            self.body[0]
        }
    }

    /// Position at arc length `s` along the recorded path.
    fn sample(&self, s: f32) -> Vec2 {
        let total = *self.arc.last().unwrap_or(&0.0);
        let s = s.clamp(0.0, total);
        let mut i = 0;
        while i + 1 < self.arc.len() && self.arc[i + 1] < s {
            i += 1;
        }
        if i + 1 >= self.path.len() {
            return *self.path.last().unwrap();
        }
        let seg = (self.arc[i + 1] - self.arc[i]).max(1e-5);
        let t = ((s - self.arc[i]) / seg).clamp(0.0, 1.0);
        Vec2::new(
            self.path[i].x + (self.path[i + 1].x - self.path[i].x) * t,
            self.path[i].y + (self.path[i + 1].y - self.path[i].y) * t,
        )
    }

    /// Rebuild the visible body from the path.
    fn resample_body(&mut self) {
        for i in 0..SEGMENTS {
            self.body[i] = self.sample(self.head_s - SEGMENT_LEN * i as f32);
        }
        self.pos = self.body[0];
    }

    /// Drop track we can no longer reach, so the path does not grow forever.
    fn trim_path(&mut self) {
        let keep_from = self.head_s - BODY_LEN * 2.0;
        if keep_from <= 0.0 || self.path.len() < 8 {
            return;
        }
        let mut cut = 0;
        while cut + 1 < self.arc.len() && self.arc[cut + 1] < keep_from {
            cut += 1;
        }
        if cut > 0 {
            self.path.drain(0..cut);
            self.arc.drain(0..cut);
        }
    }

    /// Advance the head.
    ///
    /// Forward extends the path; reversing slides back along it. That asymmetry
    /// is the whole point: a reversing worm does not carve a new track, it
    /// retreats down the one it made.
    fn advance(&mut self, dt: f32, step: f32, turn: f32) {
        if self.state == WormState::Reversing {
            // Back along our own trail, stopping at the oldest track we still
            // remember rather than sliding off the end of it.
            self.head_s = (self.head_s - step).max(BODY_LEN + 0.01);
            self.resample_body();
            let d = Vec2::new(self.body[0].x - self.body[1].x, self.body[0].y - self.body[1].y);
            if d.x.abs() + d.y.abs() > 1e-4 {
                self.heading = d.y.atan2(d.x);
            }
            return;
        }

        self.heading += turn * dt;
        let head = self.sample(self.head_s);
        let next = Vec2::new(
            head.x + self.heading.cos() * step,
            head.y + self.heading.sin() * step,
        );

        // If we reversed, the track ahead is stale. Discard it before laying
        // down new path, or the worm would snap back onto its old route.
        let total = *self.arc.last().unwrap_or(&0.0);
        if self.head_s < total - 0.01 {
            let mut cut = 0;
            while cut + 1 < self.arc.len() && self.arc[cut + 1] < self.head_s {
                cut += 1;
            }
            self.path.truncate(cut + 1);
            self.arc.truncate(cut + 1);
            self.path.push(head);
            self.arc.push(self.head_s);
        }

        self.path.push(next);
        self.arc.push(self.head_s + step);
        self.head_s += step;
        self.trim_path();
        self.resample_body();
    }
}

impl Body for Worm {
    fn substrate(&self) -> Substrate {
        Substrate::Crawler
    }

    fn step(&mut self, dt: f32, drives: &BrainSignals, world: &World) {
        self.time += dt;
        self.reverse_timer = (self.reverse_timer - dt).max(0.0);
        self.turn_timer = (self.turn_timer - dt).max(0.0);

        // `walk_drive` carries forward command activity, `backward` a reversal.
        self.drive = clamp(drives.walk_drive, 0.0, 1.0);

        if drives.sleep {
            self.state = WormState::Quiescent;
            self.speed = 0.0;
            return;
        }
        if self.state == WormState::Quiescent {
            self.state = WormState::Forward;
        }

        // A reversal is triggered by the reverse command population, and is
        // followed by an omega turn — together, a pirouette.
        if drives.backward && self.reverse_timer == 0.0 && self.turn_timer == 0.0 {
            self.state = WormState::Reversing;
            self.reverse_timer = self.rng.range(0.8, 2.0);
        }
        if self.state == WormState::Reversing && self.reverse_timer == 0.0 {
            self.state = WormState::OmegaTurn;
            // A real omega turn is a deep, one-directional bend.
            self.turn_timer = self.rng.range(0.5, 1.0);
        }
        if self.state == WormState::OmegaTurn && self.turn_timer == 0.0 {
            self.state = WormState::Forward;
        }

        // Undulation frequency rises with locomotor drive; amplitude is roughly
        // constant, as it is in the animal.
        let freq = 0.55 + self.drive * 1.35;
        self.phase = (self.phase + freq * dt) % 1.0;
        let wave = (self.phase * std::f32::consts::TAU).sin();

        let base_speed = (4.0 + self.drive * 26.0) * drives.tempo;
        self.speed = match self.state {
            WormState::Reversing => base_speed * 0.8,
            WormState::OmegaTurn => base_speed * 0.5,
            WormState::Quiescent => 0.0,
            WormState::Forward => base_speed,
        };

        // Side-to-side head swing, plus steering and the omega turn's deep bend.
        let swing = wave * 2.6;
        let turn = match self.state {
            WormState::OmegaTurn => 3.4,
            _ => swing + drives.turn_bias,
        };

        let step = self.speed * dt;
        if step > 0.0 {
            self.advance(dt, step, turn);
        }

        // Stay on screen. A worm has no flight to escape with, so it simply
        // turns away from the edge.
        let hw = world.bounds.0 / 2.0 - 30.0;
        let hh = world.bounds.1 / 2.0 - 30.0;
        // No flight to escape with, so the worm just turns away from the edge.
        // Steering only: clamping the head would tear it off its own path.
        if self.pos.x.abs() > hw || self.pos.y.abs() > hh {
            let to_center = (-self.pos.y).atan2(-self.pos.x);
            self.heading += crate::util::angle_diff(self.heading, to_center) * (3.0 * dt).min(1.0);
        }
    }

    fn position(&self) -> Vec2 {
        self.pos
    }

    fn heading(&self) -> f32 {
        self.heading
    }

    fn proprioception(&self) -> Proprioception {
        Proprioception {
            drive: self.drive,
            phase: self.phase,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::creature::World;

    fn world() -> World {
        World {
            bounds: (1512.0, 982.0),
            ledges: Vec::new(),
            cursor: None,
        }
    }

    fn drives(walk: f32) -> BrainSignals {
        let mut s = BrainSignals::new();
        s.walk_drive = walk;
        s
    }

    fn run(w: &mut Worm, secs: f32, d: &BrainSignals) {
        let dt = 1.0 / 60.0;
        for _ in 0..((secs / dt) as u32) {
            w.step(dt, d, &world());
        }
    }

    #[test]
    fn a_worm_is_a_crawler_not_a_flier() {
        let w = Worm::new(Vec2::ZERO, 1);
        assert_eq!(w.substrate(), Substrate::Crawler);
    }

    #[test]
    fn forward_drive_moves_it_forward() {
        let mut w = Worm::new(Vec2::ZERO, 1);
        w.heading = 0.0;
        let start = w.position();
        run(&mut w, 2.0, &drives(0.8));
        let moved = w.position().dist(start);
        assert!(moved > 20.0, "only moved {moved}");
    }

    /// The body is inextensible: every segment must stay exactly one segment
    /// length from its neighbour, or the worm stretches into a straight line and
    /// stops looking like an animal.
    #[test]
    fn the_body_never_stretches() {
        let mut w = Worm::new(Vec2::ZERO, 3);
        run(&mut w, 6.0, &drives(1.0));
        for i in 1..w.body.len() {
            let d = w.body[i].dist(w.body[i - 1]);
            assert!(
                (d - SEGMENT_LEN).abs() < 0.05,
                "segment {i} is {d} long, expected {SEGMENT_LEN}"
            );
        }
    }

    /// Locomotion must actually undulate. A worm that translates rigidly is a
    /// stick being dragged.
    #[test]
    fn crawling_undulates() {
        let mut w = Worm::new(Vec2::ZERO, 5);
        run(&mut w, 4.0, &drives(0.9));
        let c = w.curvature();
        let max = c.iter().cloned().fold(f32::MIN, f32::max);
        let min = c.iter().cloned().fold(f32::MAX, f32::min);
        assert!(
            max > 0.02 && min < -0.02,
            "body should bend both ways: {min}..{max}"
        );
    }

    /// Drive changes frequency, not amplitude — as in the animal.
    #[test]
    fn faster_drive_undulates_faster() {
        let sample = |drive: f32| {
            let mut w = Worm::new(Vec2::ZERO, 7);
            let d = drives(drive);
            let dt = 1.0 / 60.0;
            let mut crossings = 0;
            let mut prev = w.phase;
            for _ in 0..600 {
                w.step(dt, &d, &world());
                if w.phase < prev {
                    crossings += 1;
                }
                prev = w.phase;
            }
            crossings
        };
        assert!(
            sample(1.0) > sample(0.1),
            "undulation frequency should rise with drive"
        );
    }

    /// A reversal backs the animal up along its own track. Asserted as a
    /// projection onto the body axis rather than "x decreased" — the worm
    /// undulates, so it never travels in a straight line and a naive
    /// coordinate test measures the wiggle instead of the direction.
    #[test]
    fn a_reverse_command_backs_the_worm_up() {
        let mut w = Worm::new(Vec2::ZERO, 11);
        w.heading = 0.0;
        run(&mut w, 1.0, &drives(0.7));

        // The direction the animal is currently pointing, head to neck.
        let axis = {
            let d = Vec2::new(w.body[0].x - w.body[1].x, w.body[0].y - w.body[1].y);
            let l = (d.x * d.x + d.y * d.y).sqrt().max(1e-5);
            Vec2::new(d.x / l, d.y / l)
        };
        let before = w.position();

        let mut rev = drives(0.7);
        rev.backward = true;
        w.step(1.0 / 60.0, &rev, &world());
        assert_eq!(w.state, WormState::Reversing);
        run(&mut w, 0.5, &drives(0.7));

        let after = w.position();
        let along = (after.x - before.x) * axis.x + (after.y - before.y) * axis.y;
        assert!(
            along < -1.0,
            "head should retreat along the body axis, moved {along:+.2}"
        );
    }

    /// And forward motion must go the other way, or the test above proves
    /// nothing.
    #[test]
    fn forward_motion_advances_along_the_body_axis() {
        let mut w = Worm::new(Vec2::ZERO, 11);
        w.heading = 0.0;
        run(&mut w, 1.0, &drives(0.7));
        let axis = {
            let d = Vec2::new(w.body[0].x - w.body[1].x, w.body[0].y - w.body[1].y);
            let l = (d.x * d.x + d.y * d.y).sqrt().max(1e-5);
            Vec2::new(d.x / l, d.y / l)
        };
        let before = w.position();
        run(&mut w, 0.5, &drives(0.7));
        let after = w.position();
        let along = (after.x - before.x) * axis.x + (after.y - before.y) * axis.y;
        assert!(along > 1.0, "head should advance, moved {along:+.2}");
    }

    /// Reversal is followed by an omega turn — together a pirouette, which is
    /// how the animal reorients.
    #[test]
    fn a_reversal_is_followed_by_an_omega_turn() {
        let mut w = Worm::new(Vec2::ZERO, 13);
        let mut rev = drives(0.6);
        rev.backward = true;
        w.step(1.0 / 60.0, &rev, &world());
        assert_eq!(w.state, WormState::Reversing);

        // Reverse timer runs out, then the turn.
        run(&mut w, 2.5, &drives(0.6));
        assert!(
            matches!(w.state, WormState::OmegaTurn | WormState::Forward),
            "state after reversal: {:?}",
            w.state
        );
    }

    #[test]
    fn quiescence_stops_the_worm() {
        let mut w = Worm::new(Vec2::ZERO, 17);
        run(&mut w, 1.0, &drives(0.9));
        let mut sleepy = drives(0.9);
        sleepy.sleep = true;
        run(&mut w, 0.5, &sleepy);
        let at = w.position();
        run(&mut w, 2.0, &sleepy);
        assert_eq!(w.state, WormState::Quiescent);
        assert_eq!(w.speed, 0.0);
        assert!(w.position().dist(at) < 0.01, "a quiescent worm moved");
    }

    /// Proprioception is part of the circuit for this animal, so it must
    /// actually vary with locomotion rather than being a constant.
    #[test]
    fn proprioception_tracks_locomotion() {
        let mut w = Worm::new(Vec2::ZERO, 19);
        let d = drives(0.8);
        let dt = 1.0 / 60.0;
        let mut phases = Vec::new();
        for _ in 0..30 {
            w.step(dt, &d, &world());
            phases.push(w.proprioception().phase);
        }
        assert!(w.proprioception().drive > 0.5);
        let distinct = phases.windows(2).filter(|p| p[0] != p[1]).count();
        assert!(distinct > 20, "phase barely advanced");
    }

    #[test]
    fn the_worm_stays_on_screen() {
        let mut w = Worm::new(Vec2::new(700.0, 400.0), 23);
        w.heading = 0.6;
        run(&mut w, 20.0, &drives(1.0));
        assert!(w.position().x.abs() <= 1512.0 / 2.0, "x {}", w.position().x);
        assert!(w.position().y.abs() <= 982.0 / 2.0, "y {}", w.position().y);
    }
}
